# Generated by Django 2.1.7 on 2019-02-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
